### ISSUE TITLE
Uncaught TypeError: i.stat is not a function

### ISSUE THREAD

**Issue by eliooses** [feross/webtorrent#477] opened 2015-11-03 08:14 UTC
I have this code:
view-source:http://projectnfx.github.io/

I want streaming an seed at the same time (only with the player It's enough?) and i have this issues:

Uncaught TypeError: i.stat is not a function
a @ webtorrent.min.js:7
b @ webtorrent.min.js:6
w.seed @ webtorrent.min.js:12
w.seed @ webtorrent.min.js:12
(anonymous function) @ (index):16
o @ webtorrent.min.js:12
(anonymous function) @ webtorrent.min.js:12
i.emit @ webtorrent.min.js:4
H._onStore @ webtorrent.min.js:1
(anonymous function) @ webtorrent.min.js:1
(anonymous function) @ webtorrent.min.js:2
u.call @ webtorrent.min.js:2
f @ webtorrent.min.js:2

Many thanks in advance.

**Comment by Chocobozzz** [comment] 2015-11-03 08:24
What is the web browser?

**Comment by eliooses** [comment] 2015-11-03 18:38
Chrome, of course.

While some testers have told me that Opera has worked perfectly.

**Comment by Travier** [comment] 2015-11-25 16:45
I having this same problem with Electron. I've tried including the script normally, with webpack and browserify.

Error:
![webtorrent-i-stat](https://cloud.githubusercontent.com/assets/3410152/11403145/62b595fa-9369-11e5-87b7-51f66a9f122c.png)

WebTorrent Code:
![webtorrent-code](https://cloud.githubusercontent.com/assets/3410152/11403207/a1a1d45e-9369-11e5-8171-9d1a62eb9752.png)

**Comment by feross** [comment] 2015-12-04 02:23
@eliooses I couldn't access the link you posted, but this issue sounds like a duplicate of https://github.com/feross/webtorrent/issues/495 which is fixed now.

**Closed by feross** 2015-12-04 02:23 UTC
