### ISSUE TITLE
Using parsed torrent not working correctly

### ISSUE THREAD

**Issue by frankh** [feross/webtorrent#471] opened 2015-10-29 10:30 UTC
```
var parsedTorrent = {
  "infoHash": "60e6b17767106247e1...",
  "name": ... etc
};

client.add(parsedTorrent, function (torrent) {
  console.log('Client is downloading:', torrent.infoHash);
}
```

This raises an error "e.created.getDate()" undefined is not a function. After some digging it turns out that e.created is a date string, so I manually wrapped it in new Date().

It now technically worked, except it seems like it just used the infoHash and created a magnet link. The whole reason I used a parsed torrent was to speed up the download by skipping the magnet step

**Comment by devTristan** [comment] 2015-10-29 13:46
Did you supply one or more trackers? Without those it won't be able to get peers anywhere except the DHT.

**Comment by frankh** [comment] 2015-10-30 10:12
Yes I supplied a tracker.

Also, maybe I'm just misunderstanding something, but shouldn't the first callback ("got torrent metadata") fire instantly for a parsed torrent?

From briefly stepping through the code it seemed like it just took the infoHash and ignored the rest of the data, just fetching everything from the DHT

**Comment by DiegoRBaquero** [comment] 2015-12-11 18:01
@frankh Did you solve it, can you provide debug logs?

https://github.com/feross/webtorrent/blob/master/lib/torrent.js#L288-L289

**Comment by feross** [comment] 2016-01-03 19:19
> Also, maybe I'm just misunderstanding something, but shouldn't the first callback ("got torrent metadata") fire instantly for a parsed torrent?

Yes, it should fire very fast, but not on the same tick. The 'torrent' event always fires on the next tick to give users a chance to attach event listeners on the event.

> From briefly stepping through the code it seemed like it just took the infoHash and ignored the rest of the data, just fetching everything from the DHT

That should not happen.

It would be a lot easier to debug this issue with a complete code example. Also, to confirm, you're using this in node.js, not the browser, right?

**Comment by DiegoRBaquero** [comment] 2016-01-03 20:03
@feross This is just because the 'info' property is required. I stumbled upon this issue when creating the BMagnet demo server.

If you include `'info': {}` in your parsed torrent, it should work. It did the job for me.

Check https://github.com/feross/webtorrent/blob/master/lib/torrent.js#L291-L292 now

**Comment by feross** [comment] 2016-01-03 20:09
Ah, right. This is expected behavior if it's not a real "parsed torrent". But I have no idea why he was getting an exception. I don't think "created.getDate()" appears anywhere in the webtorrent code.

**Comment by DiegoRBaquero** [comment] 2016-01-03 20:15
Re-read the original issue and it is really weird. 

created.getDate() is only in https://github.com/feross/parse-torrent-file/blob/master/test/encode.js#L13 in the whole webtorrent and its deps tree

**Comment by feross** [comment] 2016-01-03 23:03
Yeah, let's close this for now.

@frankh If you have more details to share about what triggered this bug, please leave a comment or open a new issue.

**Closed by feross** 2016-01-03 23:03 UTC
Labels: need more info
