### ISSUE TITLE
firefox : ICE fail after a while

### ISSUE THREAD

**Issue by Robien** [feross/webtorrent#484] opened 2015-11-14 21:48 UTC
Hey

I am following the progress of webtorrent for a while and I have to thank you for the progress done so far!
I have spotted a bug long time ago but I thought it was a due to the early developpmenet stage of webtorrent and the webrtc implementation in firefox. (I decide to report it before I die ... I am from Paris and... *I see dead people*... )

The problem is after using webtorrent for a while (on the same page), it can't connect to new peers (log says: "ICE failed, see about:webrtc for more details" in loop)
When I have this issue I can't download anything obviously but I can't browse any regular website in the browser. That part made me think it might be an issue with firefox but as I only spot the problem with webtorrent I thought it might be a good idea to post an issue here first.

How to reproduce the issue:
- open instant.io
- start downloading a torrent (I use wanderers.torrent)
- wait for a while (sorry I don't know exactely how long, but after an hour I have the issue almost all the time, but it might be faster than that)
- firefox can't load any web page and instant.io refuse to start any download.

I am using firefox 44.0a2 developper edition 64 bits for windows for this test but it works with older version too and it's exactly the same thing on linux, the OS I use usualy.
I tried with chrome and it seems to works fine.

"about:webrtc" logs:

```
Identifiant PeerConnection: 1447526839197000 (id=2147483781 url=https://instant.io/)
Statistiques ICE
Candidat local	Candidat distant	État ICE	Priorité	Nommé	Sélectionné
SDP
SDP local

v=0

o=mozilla...THIS_IS_SDPARTA-44.0a2 5965381882588014835 0 IN IP4 0.0.0.0

s=-

t=0 0

a=sendrecv

a=fingerprint:sha-256 40:56:F5:10:D4:E6:57:E6:90:11:6C:F0:03:D6:D5:60:9E:33:9C:7A:60:A5:64:CD:14:69:AD:64:2F:6D:30:60

a=ice-options:trickle

a=msid-semantic:WMS *

m=application 15274 DTLS/SCTP 5000

c=IN IP4 52.16.165.92

a=candidate:0 1 UDP 2121728255 192.168.1.38 50652 typ host

a=candidate:1 1 UDP 1685528575 82.230.85.110 50652 typ srflx raddr 192.168.1.38 rport 50652

a=candidate:3 1 UDP 91693055 52.16.165.92 15274 typ relay raddr 52.16.165.92 rport 15274

a=sendrecv

a=end-of-candidates

a=ice-pwd:d3470dd3c7ec6d81dacf05053d3a731c

a=ice-ufrag:355b89c1

a=mid:sdparta_0

a=sctpmap:5000 webrtc-datachannel 256

a=setup:actpass

a=ssrc:2012902614 cname:{3206b375-59d7-4771-b8f9-9e082a3a6a0a}

SDP distant

Statistiques RTP
```

This message is repeated for each "ICE failed, see about:webrtc for more details" I suppose.
I am not a web developer so it means nothing for me. If you found anything useful here please tell me :)

Thanks

PS: please notice the "o=mozilla...THIS_IS_SDPARTA" in the log message :)

**Comment by gustavomrfz** [comment] 2015-11-21 15:34
Related: https://github.com/feross/webtorrent/issues/467

I'm from Barcelona, Robien. Hold your head up, having fear is what they want for us.

**Comment by feross** [comment] 2016-02-11 05:51
I believe this may be another instance of https://github.com/feross/webtorrent/issues/551 caused by us opening up too many RTCPeerConnection. Closing in favor of that issue.

**Closed by feross** 2016-02-11 05:52 UTC
