### ISSUE TITLE
I am getting this error document undefined

### ISSUE THREAD

**Issue by anaganisk** [feross/webtorrent#392] opened 2015-08-02 06:23 UTC
![capture](https://cloud.githubusercontent.com/assets/9448273/9025000/ff372856-390c-11e5-9f1f-133128283914.JPG)
my node code is as follows
![capture](https://cloud.githubusercontent.com/assets/9448273/9025008/3d9edbe8-390d-11e5-89c3-21b0ff28628d.JPG)

**Comment by feross** [comment] 2015-08-06 09:06
How is this running in node? Your screenshot shows html code. I'm confused - can you clarify.

**Comment by anaganisk** [comment] 2015-08-06 09:09
Hello , i was trying to build a simple ui for that using html but using node in the backend when i am trying to execute the following code I get that error.
Is it not supposed o be used like that?

**Comment by anaganisk** [comment] 2015-08-06 09:09
to be more particular i am also using node-webkit

**Comment by feross** [comment] 2015-08-06 09:13
This is duplicate of #304. Right now node-webkit support is iffy. PRs welcome to fix this!

**Closed by feross** 2015-08-06 09:13 UTC
Labels: need more info

**Comment by anaganisk** [comment] 2015-08-06 09:14
Thank you BTW I have found a way around this yesterday and it was working great.
Thanks for the response

**Comment by feross** [comment] 2015-08-06 09:18
How did you work around the problem?

**Comment by anaganisk** [comment] 2015-08-06 09:23
Instead of using streaming it as video directly by appending it to the DOM (the method used in your examples).
I used a videostream plugin like this. This was the only thing i was trying to acheieve
![capture](https://cloud.githubusercontent.com/assets/9448273/9108318/d0d56f18-3c4a-11e5-9ff8-7afb861e51ff.JPG)
