### ISSUE TITLE
Resumable downloads (using partial files)

### ISSUE THREAD

**Issue by corysimmons** [feross/webtorrent#276] opened 2015-03-08 03:39 UTC
For instance, if I'm torrenting something and close my terminal, can I reopen it and resume a download?

Didn't grep it in README.

**Comment by feross** [comment] 2015-03-08 03:45
No way to do this right now. PR welcome!

**Comment by corysimmons** [comment] 2015-03-08 03:49
Aww...

Is there even a way to perform any events right before someone exits a program in Node?

**Comment by corysimmons** [comment] 2015-03-08 03:52
Without actually reading any of this or knowing what any of it does...

http://stackoverflow.com/a/14032965/175825 > https://nodejs.org/api/stream.html#stream_readable_pause

On WebTorrent open: https://nodejs.org/api/stream.html#stream_readable_resume

**Comment by feross** [comment] 2015-07-03 18:46
Duplicate of #320

**Closed** 2015-07-03 18:46 UTC
Labels: feature request, pr welcome
