### ISSUE TITLE
Support for MKV

### ISSUE THREAD

**Issue by marcelodelta** [feross/webtorrent#796] opened 2016-05-12 01:31 UTC
There is support for MKV / H.264 video ?

A Erro is shown: 
undefined:1 Uncaught (in promise) DOMException: Failed to load because no supported source was found.

**Comment by feross** [comment] 2016-05-12 21:59
WebTorrent uses the `videostream` package to play back video files in the browser when you use `file.appendTo()` or `file.renderTo()`. It currently only supports MP4. That's where support for MKV would need to be added. There's an issue about that here:

https://github.com/jhiesey/videostream/issues/29

Duplicate of #405.

**Closed by feross** 2016-05-12 21:59 UTC
Labels: question
