### ISSUE TITLE
Large torrent -  FATAL ERROR: Out Of Memory

### ISSUE THREAD

**Issue by dragonpiper** [feross/webtorrent#475] opened 2015-11-02 10:34 UTC
I have 24GB of ram. When trying to start a 2GB+ torrent i get 

FATAL ERROR: node::smalloc::Alloc(v8::Handle<v8::Object>, size_t, v8::ExternalArrayType) Out Of Memory

Is there anyway to fix or avoid this ?

**Comment by DiegoRBaquero** [comment] 2015-12-11 18:06
Because WebTorrent stores the files in memory too at the moment, it's a limitation of V8 engine.

**Comment by feross** [comment] 2016-01-13 20:45
@dragonpiper Did you run into this error while using WebTorrent in the **browser**?

**Comment by feross** [comment] 2016-02-28 08:04
@dragonpiper Without further info, we can't reproduce this issue. I just tried seeding a 4.5GB torrent without issues. Closing.

**Closed by feross** 2016-02-28 08:04 UTC
Labels: need more info
