### ISSUE TITLE
webseed download speed not reported

### ISSUE THREAD

**Issue by vankasteelj** [feross/webtorrent#1006] opened 2017-01-01 23:29 UTC
Webseed download is considered "unverified", I believe. Because if I make my own downloadSpeed method, based on client.received instead of client.downloaded, I get the actual information. Note that Windows is registering the speed too. 

**The first issue**: Is this a desired behavior? I somewhat doubt it, because qbittorrent, for example, does account that webseed speed. And also: it does download things, yet it isnt registered by the downloadSpeed. _Note that this happens in webtorrent-desktop too._

**The second issue** is more like a real bug, apparently : when I try to load my torrent, it starts downloading, but it does a rangerError loop and make the browser crash. See the error trace:
![nw_2017-01-02_00-22-16](https://cloud.githubusercontent.com/assets/12599850/21583461/4270f756-d082-11e6-94a2-5aea6cf5dc3f.png)
 _Note that this doesnt happen in webtorrent-desktop, it does do weird things but doesn't crash. Maybe it's dumping unverified bytes without writing them?_

The (copyright-free) [torrent](http://cdn.media.ccc.de/congress/2016/webm-hd/33c3-8288-deu-eng-fra-Bonsai_Kitten_waren_mir_lieber_-_Rechte_Falschmeldungen_in_sozialen_Netzwerken_webm-hd.webm.torrent) I'm using, for reference.

* WebTorrent version: 0.98
* Node.js version: 7.1.0
* Browser name/version (if using WebTorrent in the browser): nwjs 18.6

**Comment by feross** [comment] 2017-01-29 21:40
> Re: RangeError: Array buffer allocation failed

Are you on a 32-bit system, or compiling your NW.js app as a 32-bit app? This issue could be caused by that, and lots of users ran into this exact error in WebTorrent Desktop before we switched to providing both 32-bit and 64-bit installers. See https://github.com/feross/webtorrent/issues/895#issuecomment-244276462

**Comment by feross** [comment] 2017-01-29 21:43
> Re: web seed download speed

We use the total downloaded bytes to determine the download speed, you can see that here: https://github.com/feross/webtorrent/blob/master/lib/torrent.js#L916-L917 No idea why you're seeing the behavior you describe. Maybe it's related to the exception you're getting ("RangeError: Array buffer allocation failed")?

**Comment by vankasteelj** [comment] 2017-01-29 21:51
> We use the total downloaded bytes to determine the download speed

That's still for torrent, not for the client. Torrent is reporting wrong information, client is getting it right

> Are you on a 32-bit system, or compiling your NW.js app as a 32-bit app?
Yes, a 32-bit app. But does it mean a PC with less than 4GB of ram won't be able to use webseeds?

**Comment by feross** [comment] 2017-01-29 22:09
> That's still for torrent, not for the client. Torrent is reporting wrong information, client is getting it right

I don't understand how that's possible. Look at the code: https://github.com/feross/webtorrent/blob/master/lib/torrent.js#L916-L918 We add the same `downloaded` amount to both the torrent and client's speed.

**Comment by feross** [comment] 2017-01-29 22:13
> Yes, a 32-bit app. But does it mean a PC with less than 4GB of ram won't be able to use webseeds?

The amount of RAM in the system isn't the issue. Virtual memory backed by disk exists. The issue is that 32-bit apps don't have enough address space to refer to memory beyond 2GB. Normally WebTorrent shouldn't ever allocate that much RAM, but it can sometimes burst above that amount for brief times especially when downloading fast or with many torrents.

There's not an easy way to ensure that systems with low memory won't run out. WebTorrent will operate normally until it tries to allocate memory and it suddenly fails. At that point the app will be in an indeterminate state and it's not clear how to recover.

You should really offer a 64-bit version of your app, since 95% of users have 64-bit systems these days. See real-world stats in the issue I linked.

**Comment by vankasteelj** [comment] 2017-01-29 22:37
webseeds on that torrent were maxing out my connection, yes, somewhere near 35-40mbps

**Comment by madovsky** [comment] 2017-01-30 09:30
these real-world stats are faked, like browsers stats. it's not true. a lot of countries still using internet under 128Kb and a 32bit tablet and computers.

**Comment by vankasteelj** [comment] 2017-01-30 16:12
yes but with 128kbps Internet, they don't have a need for webtorrent, and if they do decide to allocate 100% of their brandwidth for downloading torrents, they still won't max out their ram due to an important amount of data flowing through P2P. So I think it doesnt matter.

**Comment by feross** [comment] 2017-01-31 00:35
@madovsky Steam is not faking their stats. Please don't make pointless accusations without any proof. http://store.steampowered.com/hwsurvey

**Closed by feross** 2017-01-31 00:35 UTC
Labels: need more info

**Comment by vankasteelj** [comment] 2017-01-31 00:41
eeeerrrrrr! I still encounter the speed issue

**Comment by feross** [comment] 2017-01-31 00:43
@vankasteelj I can't reproduce the issue. Not sure what I else I can do. If you can locate the bug, let's fix it. Can you add console.logs to your program to see what the values for `torrent.downloadSpeed` and `client.downloadSpeed` are at different points in time.

**Comment by vankasteelj** [comment] 2017-01-31 00:46
that's what I did before opening this ticket^^

>  if I make my own downloadSpeed method, based on client.received instead of client.downloaded, I get the actual information

**Comment by feross** [comment] 2017-01-31 00:49
@vankasteelj The torrent link 404s for me now.

**Comment by madovsky** [comment] 2017-01-31 06:18
well feross, first of all, you should accept different opinion in a real open source community.
secondly, who is valve corporation who own Steam?
https://en.wikipedia.org/wiki/Valve_Corporation
and third, that's not because you sold one of your project millions to yahoo that you must not respect developers here.
do you have any proof that Steam publishes real stats?
nevermind, you can close my comment another time, I don't care

**Comment by vankasteelj** [comment] 2017-01-31 18:06
steam usage survey probably is a conspiracy indeed, frakkin' reptilians

**Comment by madovsky** [comment] 2017-01-31 18:52
I told you, they are everywhere....

**Comment by vankasteelj** [comment] 2017-01-31 22:22
I consider the bug as reported, feel free to take it into account or not.

**Comment by feross** [comment] 2017-02-01 14:43
@vankasteelj Thanks for reporting. Sorry we couldn't get this figured out. If you find another link to the torrent file that demonstrates the issue, please share.
