### ISSUE TITLE
Question: Livestreaming, like Twitch?

### ISSUE THREAD

**Issue by ckcollab** [feross/webtorrent#644] opened 2016-02-28 19:36 UTC
Heyo! Thanks for releasing this, super excited about the possibilities!

Would it be possible to livestream using webtorrent? I have been doing some research and somewhere someone said you COULD livestream, but you'd need to make 15-30s chunks of video into individual torrents. 

How would that work without causing all kinds of stutters/gaps? How quickly will webtorrent be able to download the next magnet(?) link, connect to new peers, and pick up the video stream? I could maybe have it so each time the client starts streaming, have like a 2-5second delay before it starts playing the torrent to give some time to pickup subsequent torrents + peers??

Thanks for reading, appreciate all the hard work put into this!

**Comment by rom1504** [comment] 2016-02-28 20:07
duplicate of  #14, #243 and #448

There is a search bar in issues ;)

**Comment by ckcollab** [comment] 2016-02-28 20:10
I swear I searched! Thanks for those references.

So, the answer seems to be: webtorrent (BitTorrent) is for static unchanging files. Bah! I'll keep trying to find options, thank you!

**Closed** 2016-02-29 17:20 UTC
