### ISSUE TITLE
Using torrentFile (Node.js Buffer) as first parameter for client.add(...)

### ISSUE THREAD

**Issue by triangle42** [feross/webtorrent#835] opened 2016-06-13 13:29 UTC
* WebTorrent version: v0.94.4
* Node.js version: v4.4.5
* Browser name/version (if using WebTorrent in the browser): Google Chrome 51.0.2704.84 m

I use browserify.
Client.add(torrent_file_from_torrent.torrentFile, options, callbackFunction) throws an 'Invalid torrent identifier' error.

**Comment by DiegoRBaquero** [comment] 2016-06-13 15:29
Could you please show your full code?

**Comment by feross** [comment] 2016-07-29 07:05
Closing due to lack of information to reproduce this.

**Closed by feross** 2016-07-29 07:05 UTC
Labels: need more info
