### ISSUE TITLE
Support for desktop torrent clients

### ISSUE THREAD

**Issue by iadj** [feross/webtorrent#162] opened 2014-10-23 16:31 UTC
Webtorrent support for desktop torrent clients would be great as it'd allow for continuous seeding from desktop torrent client users to web users, therefore making files shared through WebTorrent apps way more sustainable for longevity .

From the WebTorrent documentation:
"We hope established torrent clients (uTorrent, Transmission, Vuze, etc.) will add support for WebRTC and the WebTorrent extensions so they can swarm with peers from both the normal and web networks."

Something I feel could speed up this process and allow projects to use WebTorrent along with desktop clients is to integrate WebTorrent support into an open source Torrent client (as a plugin) such as Deluge (http://deluge-torrent.org/), which is written in Python.

Would love to hear ideas!

**Comment by feross** [comment] 2015-07-01 00:29
This is a duplicate of https://github.com/feross/webtorrent/issues/241, let's move discussion there.

**Closed by feross** 2015-07-01 00:29 UTC
