### ISSUE TITLE
Torrents with zero-length files crash on `fs.read`

### ISSUE THREAD

**Issue by liyuhao** [feross/webtorrent#461] opened 2015-10-12 20:39 UTC
Use the webtorrent as command app, and here is the log

DEBUG INFO: webtorrent 0.62.2, node v4.1.2, linux x64, exit 1
fs.js:582
  binding.read(fd, buffer, offset, length, position, req);
          ^

Error: Offset is out of bounds
    at Error (native)
    at Object.fs.read (fs.js:582:11)
    at /usr/lib/node_modules/webtorrent/node_modules/random-access-file/index.js:77:6
    at apply (/usr/lib/node_modules/webtorrent/node_modules/thunky/index.js:16:28)
    at /usr/lib/node_modules/webtorrent/node_modules/thunky/index.js:20:25
    at onfinish (/usr/lib/node_modules/webtorrent/node_modules/random-access-file/index.js:37:4)
    at /usr/lib/node_modules/webtorrent/node_modules/random-access-file/index.js:43:49
    at FSReqWrap.oncomplete (fs.js:82:15)

**Comment by DiegoRBaquero** [comment] 2015-12-11 18:04
@liyuhao Have you solved it?

**Comment by Danmer** [comment] 2015-12-23 07:12
same problem

```
DEBUG INFO: webtorrent 0.63.4, node v5.1.0, win32 x64, exit 1
fs.js:620
  binding.read(fd, buffer, offset, length, position, req);
          ^

Error: Offset is out of bounds
    at Error (native)
    at Object.fs.read (fs.js:620:11)
    at C:\Users\danmer\AppData\Roaming\npm\node_modules\webtorrent\node_modules\random-access-file\index.js:77:6
    at apply (C:\Users\danmer\AppData\Roaming\npm\node_modules\webtorrent\node_modules\thunky\index.js:16:28)
    at C:\Users\danmer\AppData\Roaming\npm\node_modules\webtorrent\node_modules\thunky\index.js:20:25
    at onfinish (C:\Users\danmer\AppData\Roaming\npm\node_modules\webtorrent\node_modules\random-access-file\index.js:37:4)
    at C:\Users\danmer\AppData\Roaming\npm\node_modules\webtorrent\node_modules\random-access-file\index.js:43:49
    at FSReqWrap.oncomplete (fs.js:82:15)
 "dn" not an internal or external
command, operable program or batch file.
```

**Comment by feross** [comment] 2015-12-27 21:30
This is an odd error. How large is the torrent you're trying to download?

**Comment by jleal52** [comment] 2016-01-03 12:07
I've detected torrent with zero length files, give this error.

Running just this code:

```
var torrentStream = require('torrent-stream');
var parseTorrent = require('parse-torrent');

var parsed = parseTorrent('magnet:?xt=urn:btih:1eb72598ea9168f3e939b0f1e0b48b52e8613c03');
var engine = torrentStream(parsed);
engine.on('ready',function(e) {
        console.log('ready');
});
```

The stack trace error is:
```
fs.js:582
  binding.read(fd, buffer, offset, length, position, req);
          ^

Error: Offset is out of bounds
    at Error (native)
    at Object.fs.read (fs.js:582:11)
    at /home/usuario/torrent-coder/node_modules/torrent-stream/node_modules/random-access-file/index.js:77:6
    at apply (/home/usuario/torrent-coder/node_modules/torrent-stream/node_modules/thunky/index.js:16:28)
    at /home/usuario/torrent-coder/node_modules/torrent-stream/node_modules/thunky/index.js:20:25
    at onfinish (/home/usuario/torrent-coder/node_modules/torrent-stream/node_modules/random-access-file/index.js:37:4)
    at /home/usuario/torrent-coder/node_modules/torrent-stream/node_modules/random-access-file/index.js:43:49
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by feross** [comment] 2016-01-03 16:01
Aha! I've figured it out. This is caused by a bug in `fs.read` in node.js. Issue opened:  https://github.com/nodejs/node/issues/4517

**Comment by feross** [comment] 2016-01-03 16:47
This is fixed in [random-access-file](https://github.com/mafintosh/random-access-file) 0.3.2.

**Closed by feross** 2016-01-03 16:47 UTC
Labels: need more info
