### ISSUE TITLE
Give hash, get metadata, download missing, seed

### ISSUE THREAD

**Issue by wilhelmmatilainen** [feross/webtorrent#361] opened 2015-06-15 20:46 UTC
Is it possible to
Give infohash -> download metadata from the network -> check the integrity of the local files based on the metadata -> download the missing/corrupted pieces -> seed the data on the network
???

**Comment by eabay** [comment] 2015-06-15 20:50
Yes, it would be very nice if the download does not start over again.

**Comment by feross** [comment] 2015-06-16 22:44
This isn't possible yet. PR welcome!

Closing as duplicate of https://github.com/feross/webtorrent/issues/276

**Closed by feross** 2015-06-16 22:44 UTC
