### ISSUE TITLE
Suggestion  fileSystem  

### ISSUE THREAD

**Issue by EgyptionBoy** [feross/webtorrent#311] opened 2015-05-10 08:45 UTC
Hi Feross , 
I tried your https://instant.io/
Your idea is amazing, but as you know if seeders close the browser you will not have any peers, 
so while I was working before with html5 I read somthing about how to work with fileSystem , 
Is that help to save streamed files and read any time when peers online?
I used this tut to did it , 
http://www.noupe.com/design/html5-filesystem-api-create-files-store-locally-using-javascript-webkit.html

**Comment by jaybekster** [comment] 2015-05-12 21:18
I think the best way is seedint a file on server by itself.
After uploading file to server start to seed this file on server to addition.
But i didn't find the soultion how to do it: if i seed this file, only uTorrent can download from this file and non of browser peers.

**Comment by feross** [comment] 2015-05-13 06:15
@EgyptionBoy Thanks for the suggestion. Right now, webtorrent is uses an in-memory backing store in the browser. We should eventually store data on the filesystem so we can support downloading files larger than the user's memory, or 2GB which is the limit in Chrome. Until then, webtorrent in the browser is limited to the available memory on the user's machine.

There's already an issue for this here: https://github.com/feross/webtorrent/issues/86

Even once we have browser storage working, there's still no way to have users seed files when they've close all tabs running webtorrent. That's just a limitation of the web platform, as far as I understand. This may change with [Service Workers](http://www.html5rocks.com/en/tutorials/service-worker/introduction/) and specs like this one: [Task Scheduler](http://www.w3.org/TR/task-scheduler/).

**Comment by feross** [comment] 2015-05-13 06:16
@EgyptionBoy I should also mention that I'm working on fixing bugs that cause webtorrent to use much more memory than necessary in the browser. There's an issue here where I'm debugging it: https://github.com/feross/instant.io/issues/3

**Comment by feross** [comment] 2015-05-13 06:18
@jaybekster You can seed files from a server using [webtorrent-hybrid](https://github.com/feross/webtorrent-hybrid). Just run `webtorrent-hybrid seed /path/to/file` and then the files should be available to web peers.

**Comment by feross** [comment] 2015-05-13 06:19
I'm going to close this issue since it's a duplicate of https://github.com/feross/webtorrent/issues/86, but feel free to continue replying.

**Closed by feross** 2015-05-13 06:19 UTC
