### ISSUE TITLE
Hybrid module

### ISSUE THREAD

**Issue by mafintosh** [feross/webtorrent#211] opened 2014-12-17 13:56 UTC
We should have a small module that is basically just a webtrc <==> tcp proxy so we could start adding building hybrid clients :)

**Comment by fbodz** [comment] 2015-02-28 00:41
@astro Has there been any development of this module

**Comment by fbodz** [comment] 2015-03-06 20:31
I have placed a bounty on this module https://www.bountysource.com/issues/7081908-hybrid-module

**Comment by feross** [comment] 2015-03-12 04:16
Duplicate of #202

**Closed by feross** 2015-03-12 04:16 UTC
