### ISSUE TITLE
When using web torrent and airplay to Apple TV (3 & 4) the added subtitles do not show

### ISSUE THREAD

**Issue by Evhelden** [feross/webtorrent#880] opened 2016-08-07 16:31 UTC
Used Webtorrent version 0.10.0 (0.96.0). The added subtitles do not show when pushing the airplay option. The Apple TV does not receive the subtitles info. This applies to both Apple TV 3 and 4. Only full synchronous airplay of the mac device is capable to push the subtitles as well. The app itself does not support air playing the subtitles?

**Comment by deamme** [comment] 2016-08-07 16:43
Duplicate of #262, I think.

**Comment by feross** [comment] 2016-08-07 20:38
@deamme Yep, this is a duplicate. #262

**Closed by feross** 2016-08-07 20:38 UTC
