### ISSUE TITLE
Emit more warnings in the client instance (http errors, tracker connection errors...)

### ISSUE THREAD

**Issue by Chocobozzz** [feross/webtorrent#960] opened 2016-10-23 16:58 UTC
Hi,

If a tracker is down and the client wants to connect through a websocket, the connection will fail but we don't have any warnings events in the client instance. It could be useful for certain applications to notify their users for example.

In another case, we don't have warnings if the client cannot fetch the torrent file from the `xs` parameter (just debug console logs: https://github.com/feross/webtorrent/blob/master/lib/torrent.js#L415). This could be a precious information if the application relies actively on webseed.

Thanks :)

WebTorrent version: 0.96.5
Browser: Chromium 53

**Comment by gpetrov** [comment] 2016-11-04 18:23
yes please do - currently our webseeds got stuck and we have no idea why. More debugging will be really helpful

**Comment by feross** [comment] 2017-01-19 09:57
@gpetrov The webseed stuck issue is fixed in the latest verson. See PR https://github.com/feross/webtorrent/pull/972

**Comment by feross** [comment] 2017-01-19 10:01
> @Chocobozzz If a tracker is down and the client wants to connect through a websocket, the connection will fail but we don't have any warnings events in the client instance. It could be useful for certain applications to notify their users for example.

You're right. This would be useful to have! Actually, there is already code in place that calls `torrent.emit('warning', err)` whenever there is an error connecting to a tracker. But there's a small bug in `simple-websocket` (or `bittorrent-tracker`, depending on how you look at it) that is suppressing the error. PR here: https://github.com/feross/simple-websocket/pull/14

When we emit 'close' then 'error', the problem is that `bittorrent-tracker` as the user of the stream calls `removeEventListener()` on the 'close' and 'error' handlers it attached, to clean things up. But since 'close' fires first, it cleans up the 'error' handler and we don't ever get the error.

This is now fixed!

**Comment by feross** [comment] 2017-01-19 10:12
> @Chocobozzz  In another case, we don't have warnings if the client cannot fetch the torrent file from the xs parameter

PR here: https://github.com/feross/webtorrent/pull/1021

**Comment by Chocobozzz** [comment] 2017-01-19 10:13
Awesome, thanks @feross!

**Closed** 2017-01-19 23:29 UTC
