### ISSUE TITLE
Write a chrome extension to support UDP in browser?

### ISSUE THREAD

**Issue by FezVrasta** [feross/webtorrent#811] opened 2016-05-20 10:48 UTC
Chrome supports the `chrome.sockets.udp` API (https://developer.chrome.com/apps/sockets_udp) in its apps.

I've not tried this API on Chrome extensions, but if it could work we could provide an extension to enable UDP peers directly within the browser.

WebTorrent could check for the extension availability, and, if present, it could interface with it to take advantage of the UDP peers.

In this way, websites using WebTorrent on browser, could just advise the user to install the WebTorrent extension to allow them to connect to more peers.

What are your thoughts?

**Comment by zh99998** [comment] 2016-07-31 00:28
it sounds great! +1'd for this request

**Comment by feross** [comment] 2016-08-04 00:35
This is a cool idea. I've thought about it before, but Chrome extensions are not allowed to use the `chrome.sockets.udp`. So we would need to make both a Chrome app and an extension and have the extension communicate with the app to open sockets.

So it's possible, but not as elegant as described due to Chrome restrictions.

More info: 

https://stackoverflow.com/questions/13921970/google-chrome-socket-api-in-extensions
https://bugs.chromium.org/p/chromium/issues/detail?id=152875

**Comment by feross** [comment] 2016-08-04 00:36
Closing as duplicate of https://github.com/feross/webtorrent/issues/443

**Closed by feross** 2016-08-04 00:36 UTC

**Comment by FezVrasta** [comment] 2016-08-04 07:36
I see, so it would be a good plan porting the current webtorrent desktop app to Chrome App, so it can do as bridge and provide even basic torrent functionalities. Then write the chrome extension to enable webtorrent on web pages?
