### ISSUE TITLE
Can't get torrent.on('wire', function(wire, addr) {}) to work

### ISSUE THREAD

**Issue by DiegoRBaquero** [feross/webtorrent#470] opened 2015-10-28 18:53 UTC
I have the following:
```
torrent.on('wire', function(wire, addr) {
                       $log.debug("WIRE");
                    });
```
For some reason it never gets called. I also tried using the one in the examples and still nothing.

What's weird is that I do receive: `webtorrent:torrent got wire (192.168.x.x:y) +1ms`

According to https://github.com/feross/webtorrent/blob/master/lib/torrent.js it should get called, as it doesn't stop in any point inside `Torrent.prototype._onWire` but I still don't receive the event.

Any help is appreciated. Thank you!

**Update**
Figured that when the peer is LAN the event isn't emitted, however external ones do. I still can't figure why.

**Comment by feross** [comment] 2016-02-12 19:59
@DiegoRBaquero Sorry for missing this before. No idea why this would be happening, especially since the code is clearly already inside `_onWire`. Very strange. Closing because this function has changed a lot since October 2015 so it'll be hard to reproduce exactly.

**Closed by feross** 2016-02-12 19:59 UTC
