### ISSUE TITLE
cli drawing takes up too much screen

### ISSUE THREAD

**Issue by kevinsimper** [feross/webtorrent#340] opened 2015-06-02 18:58 UTC
Not doing anything while it moves.
![cli](https://cloud.githubusercontent.com/assets/1126497/7944286/030316de-096a-11e5-8447-c1588d358728.gif)

**Comment by KrasCYBORG** [comment] 2015-06-03 10:02
+1

**Comment by feross** [comment] 2015-06-12 01:23
The problem is the magnet uri is too long. I've just removed that bit of info for now. Released as 0.49.1.

What we really should do is add a prompt that shows the magnet uri and gives the user a chance to copy it to clipboard before starting seeding and showing the full UI.

**Closed by feross** 2015-06-12 01:23 UTC
Labels: bug, cli

**Comment by kevinsimper** [comment] 2015-06-12 09:01
:+1:
