### ISSUE TITLE
Transfer "dies" for no reason

### ISSUE THREAD

**Issue by Stiveknx** [feross/webtorrent#372] opened 2015-07-15 02:42 UTC
I shared a file on instant.io, then tried to transfer in my client using webtorrent-hybrid in nodejs.

I was the only one sharing the file and, my client was the only one downloading it.
For some reason, the upload "stopped" after 2 mb transfered, and the transfer didn't "move on" anymore.
I reloaded the page in instant.io, selected the file again and the transfer ran for more 15mb and stopped again. The connection simply got "Lost", I'm now trying to find why this is happening.

I tried to enable debug to check where the problem is, but I didn't locate..

How can I try to dectect where the problem is?

PS.: If there's more than 1 seeder, this doesn't happen, only when there's one seeder.

(sorry, bad English)

**Comment by feross** [comment] 2015-07-15 20:26
That's weird. No idea why that would be happening. If you get any more info about how to reliably reproduce this, please share!

**Comment by feross** [comment] 2015-07-15 20:27
If you can, run `webtorrent-hybrid` with the environment set to `DEBUG=*,-bittorrent-dht` and run it until the disconnect happens, then post the log here.

**Comment by feross** [comment] 2015-07-16 03:11
@Stiveknx Was the seeder in node or in the browser?

If the seeder was in node, I think that this may be caused by https://github.com/feross/webtorrent/issues/375

**Comment by Stiveknx** [comment] 2015-07-16 10:51
Seeder was runing in browser (directly from instant.io).

**Comment by feross** [comment] 2015-07-29 09:10
@Stiveknx Can you try this out again on https://instant.io?

If you have a flaky connection to the internet, the webrtc conncections to peers can be lost and would need to be re-established. I just pushed an improvement to the tracker module, so we now try to look for new peers every 30 seconds on the already-established WebSocket connection to the tracker.

This should make things better. Please test it out and let me know if things are better.

**Comment by Stiveknx** [comment] 2015-07-29 16:13
Hi.

So, I did a quick test and apparently the problem has been solved.
I shared the same file I did before and the file started and downloaded without stop.

I'll mark it as closed, but later I'll try to test with more and larger files!

Ps.: Thanks for the amazing project

**Comment by feross** [comment] 2015-07-30 02:24
Awesome!

**Comment by Stiveknx** [comment] 2015-08-11 00:53
Opening it again ..

sometimes, when I'm almosting finishing the download, it stops when 20 pieces or more are pending ...

Check  the debug:
http://pastebin.com/raw.php?i=jcTNZb5D


I've notice that, after "webtorrent:torrent error getting piece", if I have too much of these errors, I got stuck in last pieces.
When the transfer finishes successfully, I don't see much of there messages ...

**Comment by Stiveknx** [comment] 2015-08-17 02:44
Here's another debug:
http://pastebin.com/raw.php?i=Q6s515Rf

This time, I was seding from my computer to another one ...
I was the only seeder.

**Comment by feross** [comment] 2016-01-03 19:20
This issue is super old. I'm going to close and assume that it's fixed now. If this is not the case, feel free to open a new issue.

**Closed by feross** 2016-01-03 19:20 UTC
Labels: bug, need more info
