### ISSUE TITLE
Limiting the upload/seeding speed

### ISSUE THREAD

**Issue by manikandancsea** [feross/webtorrent#588] opened 2016-01-26 10:09 UTC
Is there any way to limit the upload speed for seeding the torrent?

**Comment by fonewoda** [comment] 2016-02-02 02:33
also want to know it

**Comment by DiegoRBaquero** [comment] 2016-02-02 02:45
Hi @manikandancsea and @fonewoda . This is not possible at the moment

**Comment by feross** [comment] 2016-02-02 06:53
Duplicate of #163.

**Closed by feross** 2016-02-02 06:53 UTC
